### PR TITLE
dont track .vscode anymore

### PR DESCRIPTION
**Pull request by antoine-richard**

### CODE REVIEW

**Comment by PierreReliquet** [comment]
as a matter of fact this file has been tracked on purpose. The vs configuration versioned in the workspace one to ensure
- tab size to 2 spaces
- no trailing spaces
- no more than one blank line in html files

The only one which could be worth changing is the format on type which indeed depends on the user rather than on the project.

What do you think?

**Comment by antoine-richard** [comment]
Makes sense.
But as soon as this project will gain hype (and it will!), you'll probably want to ensure these rules outside of vscode.

I'd suggest to use EditorConfig.

**Comment by antoine-richard** [comment]
bad news, I'm afraid that there's no way to ensure "no more than one blank line in html files" in editorconfig...

**Comment by PierreReliquet** [comment]
closed in favor of #14 do you agree @antoine-richard ?

**Comment by antoine-richard** [comment]
yep

**Pull request closed without merging**
